name: craftnrent
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  fluttertoast: ^8.2.5
  http: ^1.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/books.png
    - images/craftnrent.png
    - images/craftnrent-medium.png
    - images/drawer-bg.jpg
    - images/profil-placeholder.jpg